---
title: "D474_NaiveBayes"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(e1071)
library(caret)
```

```{r}
clickstream <- read.table(here("Data", "EditedData", "clickstream_dc.csv"),
                             header = TRUE,
                             sep = ",")
```

```{r}
train <- sample( 1:nrow(clickstream), size = .7*nrow(clickstream) )
train_df <- clickstream[train, ]
test_df <- clickstream[-train, ]
# table(clickstream$hi_clicks)
# table(test_df$hi_clicks)
```

## Model Selection, MED boundary

```{r}

train_control <- trainControl(method = "cv", number = 10)
train_df$hi_clicks_med <- as.factor(train_df$hi_clicks_med)
# Train the model
nb.fit.cv <- train(hi_clicks_med ~ main_category + page + country + location, data = train_df, trControl = train_control, method = "naive_bayes")
nb.fit.cv

nb.cv.class <- predict(nb.fit.cv, test_df)

table(nb.cv.class, test_df$hi_clicks_med)

```


```{r}
set.seed(123)
nb.fit <- naiveBayes(hi_clicks_med ~ main_category + page + country + location, data = train_df)
nb.class <- predict(nb.fit, test_df)

table(nb.class, test_df$hi_clicks_med)  # same as the cv, so the estimates match

classification.error <- (sum(table(nb.class, test_df$hi_clicks_med)) - table(nb.class, test_df$hi_clicks_med)[1,1] - table(nb.class, test_df$hi_clicks_med)[2,2])/ sum(table(nb.class, test_df$hi_clicks_med))

neg.pred.val <- (table(nb.class, test_df$hi_clicks_med)[1,1])/ (table(nb.class, test_df$hi_clicks_med)[1,1] + table(nb.class, test_df$hi_clicks_med)[1,2])

neg.pred.val <- (table(nb.class, test_df$hi_clicks_med)[2,2])/ (table(nb.class, test_df$hi_clicks_med)[2,1] + table(nb.class, test_df$hi_clicks_med)[2,2])

TN.rate <- (table(nb.class, test_df$hi_clicks_med)[1,1])/ (table(nb.class, test_df$hi_clicks_med)[1,1] + table(nb.class, test_df$hi_clicks_med)[2,1])

TP.rate <- (table(nb.class, test_df$hi_clicks_med)[2,2])/ (table(nb.class, test_df$hi_clicks_med)[1,2] + table(nb.class, test_df$hi_clicks_med)[2,2])

c('total class error'=classification.error,'TN rate'=TN.rate,'TP rate'=TP.rate)
```
## Model Selection, AVG boundary

```{r}
nb.fit <- naiveBayes(hi_clicks_avg ~ main_category + page + country + location, data = train_df)
nb.class <- predict(nb.fit, test_df)

table(nb.class, test_df$hi_clicks_avg)

classification.error <- (sum(table(nb.class, test_df$hi_clicks_avg)) - table(nb.class, test_df$hi_clicks_avg)[1,1] - table(nb.class, test_df$hi_clicks_avg)[2,2])/ sum(table(nb.class, test_df$hi_clicks_avg))

neg.pred.val <- (table(nb.class, test_df$hi_clicks_avg)[1,1])/ (table(nb.class, test_df$hi_clicks_avg)[1,1] + table(nb.class, test_df$hi_clicks_avg)[1,2])

neg.pred.val <- (table(nb.class, test_df$hi_clicks_avg)[2,2])/ (table(nb.class, test_df$hi_clicks_avg)[2,1] + table(nb.class, test_df$hi_clicks_avg)[2,2])

TN.rate <- (table(nb.class, test_df$hi_clicks_avg)[1,1])/ (table(nb.class, test_df$hi_clicks_avg)[1,1] + table(nb.class, test_df$hi_clicks_avg)[2,1])

TP.rate <- (table(nb.class, test_df$hi_clicks_avg)[2,2])/ (table(nb.class, test_df$hi_clicks_avg)[1,2] + table(nb.class, test_df$hi_clicks_avg)[2,2])

c('total class error'=classification.error,'TN rate'=TN.rate,'TP rate'=TP.rate)
```

