---
title: "D474_SVM"
output: html_document
---

# SVM Space

```{r}
library(here)
library(tidyverse)
clickstream <- read.table(here("Data", "EditedData", "clickstream_dc.csv"),
                             header = TRUE,
                             sep = ",")
```


```{r}

# sample 
sample_rows <- sample(nrow(clickstream), 10000)
click_small <- clickstream[sample_rows, ]
```


```{r}
library(e1071)
click_svm <- click_small[, !(names(click_small)%in% c( "clothing_model", "key", "date","order","hi_clicks_avg"))]
click_svm$hi_clicks_med <- as.factor(click_svm$hi_clicks_med)
```


```{r}
'
click_svm$hi_clicks <- factor(click_svm$hi_clicks)
click_svm$country <- factor(click_svm$country)
click_svm$main_category <- factor(click_svm$main_category)
click_svm$color <- factor(click_svm$color)
click_svm$location <- factor(click_svm$location)
click_svm$model_photography <- factor(click_svm$model_photography)
click_svm$page <- factor(click_svm$page)
'
```


```{r}
set.seed(123)
train <- sample(1:nrow(click_svm), nrow(click_svm)/2)
test <-(-train)
```

```{r}
# linear 
tune <- tune(
  svm,
  hi_clicks_med ~ .,
  data=click_svm[train, ],
  kernel = "linear",
  ranges =list(cost =c(0.1, 1, 1.5, 10, 100)),
  control = tune.control(cross = 5)
)
summary(tune)
```

```{r}
best <- tune$best.model
pred <- predict(best, click_svm[test, ])
mean(pred != click_svm$hi_clicks_med[test])
```

```{r}
# radial kernal
set.seed(123)
tune_rad <- tune(
  svm,
  hi_clicks_med ~ .,
  data=click_svm[train, ],
  kernel = "radial",
  ranges =list(cost =c(0.1, 1, 1.5, 10, 100)),
  control = tune.control(cross = 5),
  gamma = c(0.5,1,2)
)
summary(tune_rad)
```

```{r}
best <- tune_rad$best.model
pred <- predict(best, click_svm[test, ])
mean(pred != click_svm$hi_clicks_med[test])
```

```{r}
set.seed(456)
tune_poly <- tune(
  svm,
  hi_clicks_med ~ .,
  data=click_svm[train, ],
  kernel = "polynomial",
  ranges =list((cost =c(0.1, 1, 10)),
  control = tune.control(cross = 5),
  degree = c(2,3,4))
  )
summary(tune_poly)
```

```{r}
best_poly <- tune_poly$best.model
pred_poly <- predict(best_poly, click_svm[test, ])
mean(pred_poly != click_svm$hi_clicks_med[test])
```

```{r}
table(pred_poly, click_svm$hi_clicks_med[test])

classification.error <- (table(pred, test_df$hi_clicks_med)[2,1] + table(pred, test_df$hi_clicks_med)[1,2])/ sum(table(pred, test_df$hi_clicks_med))

neg.pred.val <- (table(pred, test_df$hi_clicks_med)[1,1])/ (table(pred, test_df$hi_clicks_med)[1,1] + table(pred, test_df$hi_clicks_avg)[1,2])

neg.pred.val <- (table(pred, test_df$hi_clicks_med)[2,2])/ (table(pred, test_df$hi_clicks_med)[2,1] + table(pred, test_df$hi_clicks_med)[2,2])

TN.rate <- (table(pred, test_df$hi_clicks_med)[1,1])/ (table(pred, test_df$hi_clicks_med)[1,1] + table(pred, test_df$hi_clicks_med)[2,1])

TP.rate <- (table(pred, test_df$hi_clicks_med)[2,2])/ (table(pred, test_df$hi_clicks_med)[1,2] + table(pred, test_df$hi_clicks_med)[2,2])

c('total class error'=classification.error,'TN rate'=TN.rate,'TP rate'=TP.rate)
```


# plots 

```{r}
plot(best_poly, click_svm[train, ],
  order ~ price)
```

```{r}
str(click_svm)
# <!-- ``` -->